apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: seafile
spec:
  serviceName: mariadb-headless  # Required for StatefulSet!
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_DATABASE
            # NOTE: MARIADB_USER and MARIADB_PASSWORD are REMOVED.
            # Seafile connects as root (using DB_ROOT_PASSWD) and creates the 'seafile' user itself.
            # This is the correct flow according to Seafile documentation.
            - name: MARIADB_AUTO_UPGRADE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_AUTO_UPGRADE
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1000m"
              ephemeral-storage: "3Gi"
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
